resolver: lts-7.23

packages:
- location: '.'
- location: './../..'
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 2fe0f566f8d6b6eceb178a85516643390111bb83
    # Latest develop comment at the time of writing
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: 706ab47df9729bdc5c4ac3f4d8dfd4661d9f6e1a
    # Latest develop comment at the time of writing
  subdirs:
    - reflex-dom
    - reflex-dom-core
  extra-dep: true


extra-deps:
- dependent-sum-template-0.0.0.5
- dependent-sum-0.3.2.2
- ghcjs-dom-0.8.0.0
- jsaddle-0.8.3.2
- jsaddle-wkwebview-0.8.3.2
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- ghcjs-dom-jsaddle-0.8.0.0
- jsaddle-dom-0.8.0.0
- jsaddle-warp-0.8.3.1
- jsaddle-webkit2gtk-0.8.3.1
- gi-webkit2-4.0.12
- webkit2gtk3-javascriptcore-0.14.2.1
- gi-javascriptcore-4.0.12
- haskell-gi-0.20.1
- haskell-gi-base-0.20.2
- gi-gio-2.0.12
- gi-glib-2.0.12
- gi-gtk-3.0.14

# on ubuntu:  install webkit2gtk-4.0-dev, gobject-introspection,libgirepository1.0-dev


flags: {}

extra-package-dbs: []
